minimumReleaseAgeExclude:
  - '@bruits/satteri-darwin-arm64@0.9.5'
  - '@bruits/satteri-darwin-x64@0.9.5'
  - '@bruits/satteri-linux-arm64-gnu@0.9.5'
  - '@bruits/satteri-linux-arm64-musl@0.9.5'
  - '@bruits/satteri-linux-x64-gnu@0.9.5'
  - '@bruits/satteri-linux-x64-musl@0.9.5'
  - '@bruits/satteri-wasm32-wasi@0.9.5'
  - '@bruits/satteri-win32-arm64-msvc@0.9.5'
  - '@bruits/satteri-win32-x64-msvc@0.9.5'
  - satteri@0.9.5
